define({
    SpeciesStatus: "حالة الأنواع",
    All: "الكل",
    Active: "فعال",
    NonActive: "غير فعال",
    TrackingPeriod: "فترة التتبع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    CollectSpeciesInformation: "جمع معلومات الأنواع",
    Within: "الكل",
    Whole: "من وإلى",
    PID: "رمز الجهاز",
    ddmmyyyy: "سنة - شهر - يوم",
    placeholderSelectStatus:"حدد حالة الأنواع",
    Sensor: "نوع جهاز الاستشعار",
    Species: "النوع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    Loc: "تصنيف الموقع",
    Interval: "الفترة الزمنية",
    Actions: "الإجراءات",
    StopOver: "نقطة توقف",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    PleaseSelectSpeciesStatus: "حدد حالة الأنواع",
    chkSeasonWise: "الهجرة الموسمية  ",
    PointDensity: "الكثافة النقطية",
    MCP: "MCP",
    SelectedMCP: "نقاط مختارة MCP",
    Run: "تشغيل",
    Animate: "تحريك",
    checked: "محدد",
    unchecked: "غير محدد",
    NoResultFound: "لا توجد نتائج",
    DeleteFromMap: "حذف من الخريطة",
    DeleteFromDatabase: "حذف من قاعدة البيانات",
    TotalLength: "الطول الإجمالي",
    plotoneBirdonthemap: "MCP ارسم نوع واحد فقط على الخريطة للحصول على",
    NoDatafound: "عدد السجلات يتجاوز الذاكرة ، يرجى تحديد الوقت لتقليل البيانات.",
    ClearData: "عدد السجلات يتجاوز الذاكرة ، يرجى مسح البيانات المخططة.",
    all: "الكل",
    active: "فعال",
    nonactive: "غير فعال",
    widgets: {
        homeButton: {
            "home": {
                "button": "Home",
                "title": "Default extent"
            }
        }
    },
});