define({
    ManageUsers: "ادارة المستخدمين",
    CreateSponser: "إدخال رعاية",
    AssigntoUsers: "تعيين للمستخدمين",
    Save: "يحفظ",
    SelectBirds: "اختر الطير",
    Yes: "نعم",
    No: "رقم",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    PleaseSelectAtleastoneBirdID: "حدد رمز طائر واحد على الأقل",
    UserName: "اسم االمستخدم",
    Password: "كلمة المرور",
    Email: "البريد الإلكتروني",
    SaveandUpdate: "حفظ وتحديث",
    EnterUserName: "ادخل اسم االمستخدم",
    Enterpassword: "أدخل كلمة المرور",
    EnterEmail: "يرجى إدخال كلمة المرور",
    PhoneNo: "رقم الهاتف",
    ID: "المعرّف",
    AreyousuretoDelete: "هل أنت متأكد أنك تريد الحذف؟",
    Username: "اسم االمستخدم",
    Role: "الدور",
    placeholderAssignBirds: "تعيين الطيور",
    AssignedBirds: "الطيور التي تم تعيينها",
    Verify: "Verify",
    AssignBirds: "تعيين الطيور",
    Update: "تحديث",
    Actions: "الإجراءات",
    Delete: "حذف",
    PleaseEnterUserName: "ادخل اسم المستخدم",
    PleaseEnterPassword: "أدخل كلمة المرور",
    PleaseEnterEmailAddress: "ادخل البريد الالكتروني الصحيح",
    EnterUsername: "ادخل اسم المستخدم",
    Enterpassword: "إدخال كلمة المرور",
    EnterEmail: "أدخل البريد الإلكتروني",
    RegisteredLabel: "RegisteredLabel",
    SelectBirds: "اختر الطير",
    warning: "تحذير",
    Invalid: "غير صالح",
    NoResultsFound: "لا توجد نتائج",
    Verify:"التحقق",
    Unabletofetchbirdids: "تعذر توفير رموز الطيور",
    error: "خطأ",
    Error: "خطأ",
    success: "تم",
    Success: "تم",
    SelectBirdIds: "اختر رمز الطائر",
    UnabletoCreateUser: "تعذر إنشاء مستخدم جديد",
    assignBirds: "تعيين الطيور",
    SelectBird: "يُرجى اختيار  الطيور",
    Update: "تحديث",
    UserDeletedsuccessfully: "تم حذف المستخدم ",
    Assignedbirdssuccessfully: "تم تعيين الطيور ",
    Usercreatedsuccessfully: "تم انشاء اسم المستخدم ",
    Userverifiedsuccessfully: "تم التحقق من المستخدم بنجاح.",
    Unabletoverifytheaccount: "تعذر التحقق من الحساب.",
    UserNamealreadyexists: "اسم االمستخدم موجود بالفعل",
    UseralreadyregisteredwiththisEmail: "المستخدم مسجل بالفعل مع هذا البريد الإلكتروني",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
    Close: "قريب",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
});