define({
    root: ({
        ManageUsers: "Manage Users",
        CreateSponser: "Create Sponsor",
        AssigntoUsers: "Assign to Users",
        Save:"Save",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        Yes: "Yes",
        No:"No",
        SelectBirds:"Select Birds",
        PleaseSelectAtleastoneBirdID: "Select At least one Bird ID",
        Username: "User Name",
        Password: "Password",
        Email: "Email",
        SaveandUpdate: "Save and Update",
        PleaseEnterUserName: "Enter User Name",
        PleaseEnterPassword: "Enter Password",
        PleaseEnterEmailAddress: "Enter Valid Email Address",
        EnterUserName: "Enter User Name",
        Enterpassword: "Enter Password",
        EnterEmail: "Enter Email",
        placeholderAssignBirds:"Assign Birds",
        PhoneNo: "PhoneNo",
        RegisteredLabel: "RegisteredLabel",
        ID: "ID",
        UserName: "User Name",
        AreyousuretoDelete:"Are you sure to Delete?",
        Delete: "Delete",
        AssignBirds: "Assign Birds",
        Verify:"Verify",
        Role: "Role",
        AssignedBirds: "Assigned Birds",
        Actions: "Actions",
        SelectBirds: "Select Birds",
        warning: "warning",
        Invalid: "Invalid",
        NoResultsFound: "No Results Found",
        Unabletofetchbirdids: "Unable to fetch bird ids",
        error: "error",
        Error: "Error",
        success: "success",
        Success: "Success",
        SelectBirdIds: "Select Bird Ids",
        UnabletoCreateUser: "Unable to Create User",
        assignBirds: "Assign Birds",
        SelectBird: "Select Assign Birds",
        Update: "Update",
        UserDeletedsuccessfully: "User Deleted Successfully",
        Assignedbirdssuccessfully: "Assigned birds Successfully",
        Usercreatedsuccessfully: "User created successfully",
        Userverifiedsuccessfully: "User verified successfully",
        Unabletoverifytheaccount: "Unable to verify the account",
        Close: "Close",
        UserNamealreadyexists: "User Name already exists",
        UseralreadyregisteredwiththisEmail: "User already registered with this Email",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});