define({
    root: {
        title: 'BirdTrackingPublicUser',
        select: "select",
        locationclasses: "Locationclasses",
        PlatformID: "Platform ID",
        durationTime: "DurationTime",
        FromDate: "From Date",
        ToDate: "To Date",
        TimeInterval: "Time Interval",
        onemonth:"1 Month",
        Previousmonths: "6 Months",
        oneyear: "1 Year",
        twoyears: "2 Years",
        PleaseselectPlatformID: "Select Platform ID",
        PleaseselectDurationTime: "select Duration",
        TrackingBirdID: "Run",
        NoResultsFound: "No Results Found",
        UnabletofetchbirdPTTIDdetails: "Unable to fetch bird PTT ID details",
        warning: "warning",
        Invalid: "",
        placeholderPTTID: "Select Platform ID",
        NoResultsFound: "No Results Found",
        Animation: "Animation",
        placeholderDurationTime: "Select Duration",
        SelectBirdName: "Bird Name",
        PleaseselectBirdName: "Select Bird Name",
        placeholderBirdName: "Select Bird Name",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
    },
     "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});