define({
    root: ({
        Reports:"Tracking Report",
        FromDate: "From Date",
        PleaseEnterFromDate: "Enter From Date",
        ToDate:"To Date",
        PleaseEnterToDate: "Enter To Date",
        FetchIDs: "Fetch IDs",        
        Argos: "Argos",
        GPS: "GPS",
        GSM:"GSM",
        GPSandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        GraphsBackgroundColor: "Graphs Background Colour",
        ExportReport:"Export Reports",
        GenerateReport: "Generate Report",
        ArgosandGPSSensorDatasummary: "GPS,GSM and Argos Sensor Data Summary",
        GPSGSMandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        ToDateShouldbeGreaterthanFromDate:"To Date Should be Greater than From Date",
        PleaseSelectIDS: "Select IDS",
        ddmmyyyy: "dd - mm - yyyy ",
        NoBirdIdsFound: 'No Platform Ids found for the given selection.',
        UnabletoCollectbirdplatformids: "Unable to Collect bird platform ids.",
        PleaseSelectSensorType: "Select Sensor Type",
        placeholderSensorType:"Select Sensor",
        SensorType: "Sensor Type",
        SensorTypeDataReport: "Tracking Report",
        Youmustcheckatleastonecheckbox: "Select Platform id",
        warning: "warning",
        Invalid: "Invalid",
        PleaseSelectIds: "Select Id's",
        IDs: "IDs",
        Status: "Status",
        Inactive: "Inactive",
        Active: "Active",
        ReportDashBoard: "Report Dashboard",
        NoResultsFound: "No Results Found",
        PlatformIDs: "Platform ID",
        TotalLocations:"Locations",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        SensorType: "Sensor Type",
        SpeciesName: "Species",
        SelectPlatformID: "Platform ID",
        PleaseSelectSensorType:"select sensortype",
        placeholderSpeciesName: "Select Species",
        placeholderPTTID: "Select Platform ID",
        UnabletofetchbirdPTTIDS: "Unable to fetch bird PTT IDS",
        TrackingReport: "Tracking Report",
        TrackingReports: "Tracking Report : ",
        RawData: "Export Raw Data",
        Active: "Active",
        Inactive: "Inactive",
        UnabletoFetchRawDataDetails: "Unable to Fetch Raw Data Details",
        Unabletofetchplatformids: "Unable to fetch Platformids",
        UnabletofetchSpeciesnames: "Unable to fetch Species Names",
        to: "to",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});