define({
    root: ({
        title: "birdTrackingBynames",
        SpeciesName: "Species",
        SensorCategory: "Sensor Category",
        SensorType: "Sensor Type",
        Year: "Year",
        TimeInterval: "Time Interval",
        PlatFormID: "Platform ID List",
        Select: "Select",
        All:"All",
        Main: "Main",
        Secondary: "Secondary",
        PleaseSelectSpeciesName: "Select Species",
        PleaseSelectSensorCategory: "Select Sensor Category",
        PleaseSelectSensorType: "Select Sensor Type",
        PleaseSelectYear: "Select Year",
        PleaseSelectTimeInterval: "Select Time Interval",
        PleaseSelectPlatformID: "Select Platform ID",
        Run: "Run",
        Animate: "Animate",
        StopOver: "StopOver",
        chkSeasonWise: "Season Wise Migration",
        Unabletofetchbirdnames: "Unable to fetch bird names",
        UnabletofetchBirdSensorTypes: "Unable to fetch Bird Sensor Types",
        UnabletofetchBirdYears: "Unable to fetch Bird Years",
        UnabletofetchBirdPlatformIds: "Unable to fetch Bird Platform Ids",
        NoResultFound: "No Results Found",
        UnabletofetchBirdNamesDetails: "Unable to fetch Bird Names Details",
        placeholderSensorCategory: "Select Sensor Category",
        placeholderSensorType: "Select Sensor Type",
        placeholderYear: "Select Year",
        placeholderSpeciesName:"Select Species",
        placeholderPlatFormId: "Select platform ID",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        Active: "Active",
        Inactive: "Inactive",
        NoDataFound: "No.of records exceed the memory, please select the filter option to reduce the data.",
        HugeData: "Huge data. please select filter options",
        MigrationNote: "Note: The colour indicators may duplicate for Season Migration.",
        TIhours: "Hrs",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected"
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});