define({
    SpeciesNames: "الأنواع",
    ChooseaBird: "اختر طائرًا",
    select: "select",
    ChooseYear: "اختر السنة",
    GetBirdInfo: "احصل على معلومات الطيور",
    Run: "تشغيل",
    Close: "قريب",
    SelectSpeciesNames: "حدد النوع",
    SelectYear: "حددد السنة",
    SelectBird: "اختر الطير",
    CaptureDate: "تاريخ الالتقاط :",
    CaptureTime: "وقت الالتقاط :",
    BirdWeight: "وزن الطير :",
    CommonName: "الاسم الشائع :",
    placeholderSelectBirdId: "اختر رمز الطائر",
    placeholderSpeciesName: "حدد النوع",
    placeholderSelectBirdYear: "حدد سنة الطيور",
    LatinName: "الاسم اللاتيني :",
    PlatformId: "رمز الجهاز :",
    SensorType: "نوع جهاز الاستشعار :",
    Lat: "خط العرض :",
    Long: "خط الطول :",
    Site: "الموقع :",
    Species: "النوع :",
    SpeciesID: "رمز الأنواع :",
    WingsLength: "طول الأجنحة :",
    Age: "العمر :",
    Sex: "الجنس :",
    Status: "الحالة الاجتماعية : ",
    LastActiveDate: "تاريخ آخر نشاط :",
    Weight: "الوزن :",
    Wings: "أجنحة :",
    BandID: "رمز النطاق :",
    Status: "الحالة الاجتماعية : ",
    LastActiveDate: "تاريخ آخر نشاط :",
    ReleaseDate: "تاريخ الإصدار :",
    ReleaseTime: "وقت الارتباط :",
    Sensitive: "حساس :",
   
    UnabletofetchbirdPTTIDS: "تعذر الحصول على رمز الطيور ",
    UnabletofetchBirdIdDetails: "تعذر الحصول على تفاصيل رمز الطيور",
    UnabletofetchBirdIds: "تعذر توفير رموز الطيور",
    unabletofetchBirdNames: "تعذر الحصول على أسماء الطيور",
    NoResultsFound: "لا توجد نتائج",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    Export: "يصدر",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
            }
            }
        },
});
