define({
    Reports: "التقارير",
    FromDate: "من تاريخ",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    SensorType: "نوع جهاز الاستشعار",
    ToDate: "إلى تاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    FetchIDs: "جلب الرموز",
    ddmmyyyy: "سنة - شهر - يوم",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    GraphsBackgroundColor: "لون خلفية الرسوم البيانية",
    ExportReport: "إصدار تقرير",
    GenerateReport: "انشاء تقرير",
    ArgosandGPSSensorDatasummary: "Argos و GPS ، ملخص بيانات المستشعر",
    GPSGSMandArgosCounts: "Gps Gsm و Argos جمع بيانات",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    NoBirdIdsFound: 'لا يوجد رمز للطيور في الاختيار المحدد',
    UnabletoCollectbirdplatformids: "تعذر جمع رموز اجهزة الطيور.",
    Youmustcheckatleastonecheckbox: " حدد رمز الجهاز",
    SensorTypeDataReport: "تقرير بيانات نوع جهاز الاستشعار",
    IDs: "المعرف",
    Status: "الحالة الاجتماعية ",
    placeholderSensorType:"حدد نوع المستشعر",
    Inactive: "غير نشط",
    Active: "نشط",
    ReportDashBoard: "تقرير الألواح الرقمية",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    NoResultsFound: "لا توجد نتائج",
    GPSGSMandArgosDataCollection: "جمع بيانات نوع المستشعر",
    PlatformIDs: "رمز الجهاز",
    PleaseSelectIds: "حدد معرّف النظام الأساسي",
    //TotalLocations: "الموقع الكامل",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    ARGOSReport: "تقرير أرغوس",
    SpeciesName: "النوع",
    SelectPlatformID: " حدد رمز الجهاز",
    NumberofLocations: "عدد المواقع",
    NumberofSpecies: "عدد الأنواع",
    NumberofBirds: "عدد الطيور",
    AverageSpeed: "متوسط السرعة (Kt)",
    AverageAltitude: "متوسط الارتفاع (Meter)",
    TotallocationsCountChart: "إجمالي المواقع حسب السنة",
    TotallocationsChart: "إجمالي المواقع",
    TotalLocations: "الموقع",
    ViewReport: "عرض التقرير",
    AverageSpeedChart: "فئات الموقع",
    AverageAltitudeChart: "الارتفاع",
    TotalLocationsforSelectedIDs: "إجمالي المواقع للرمز ",
    LocationsCountforSelectedIDs: "عدد المواقع للرمز ",
    FlightSpeedofSelectedPTTIDs: "سرعة الطيران للجهاز ",
    AltitudeofSelectedPTTIDs: "ارتفاع الجهاز",
    ReportWithArgosIDs: "عرض تقرير رمز أرغوس",
    LocationClassesReport:"فئات موقع ",
    RawData: "تقرير البيانات الأولية",
    LocationClassesReport: "فئات الموقع",
    UnabletoFetchChartDetails: "لا يمكن توفير بيانات الرسم البياني",
    Locations: "الموقع",
    Speed: "السرعة (Kt)",
    UnabletofetchbirdPTTIDS: "تعذر الحصول على رمز الطيور ",
    UnabletofetchBirdsLocation: "تعذر إحضار موقع الطيور",
    UnabletofetchTotalBirds: "تعذر إحضار إجمالي الطيور",
    UnabletofetchTotalSpecies: "تعذر إحضار إجمالي الأنواع",
    UnabletofetchAvgSpeed: "تعذر جلب متوسط ​​السرعة",
    UnabletofetchAverageAltitude: "تعذر جلب متوسط ​​الارتفاع",
    UnabletoFetchChartDetails: "لا يمكن توفير بيانات الرسم البياني",
    Altitude: "(الارتفاع (بالمتر",
    Year: "سنة",
    LocationClasses: "تصنيف الموقع",
    MeanofSpeed: "متوسط ​​السرعة(kt)",
    MaxSpeed: "أقصى سرعة (Kt)",
    IDs: "المعرفات",
    MeanofAltitude: "(متوسط ​​الارتفاع (متر",
    MaxAltitude: "(أقصى ارتفاع (متر",
    placeholderPlatFormId: "اختر مُعرّف الاتصال المباشر",
    placeholderSpeciesName: "حدد الأنواع",
    NumberofLocations: "عدد المواقع",
    NumberofSpecies: "عدد الأنواع",
    NumberofBirds: "عدد الطيور",
    NoofLocations: "عدد المواقع",
    NoofSpecies: "عدد الأنواع",
    NoofBirds: "عدد الطيور",
    ArgosReport: "تقرير أرغوس",
    GPSReport: "تقرير GPS",
    GSMReport: "تقرير GSM",
    Min: "دقيقة",
    Max: "الأعلى",
    Avg: "متوسط",
    Active: "نشط",
    Inactive: "غير نشط",
    Locations: "الموقع",
    Unabletofetchbirdplatformids: "تعذر توفير رموز الطيور",
    UnabletofetchSpeciesNames: "تعذر الحصول على هذا النوع أسماء",
    UnabletoFetchRawDataDetails: "تعذر جلب تفاصيل البيانات الأولية",
    UnabletoFetchAltitudeChartDetails: "تعذر جلب تفاصيل مخطط الارتفاع",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
    widgets: {
        homeButton: {
            "home": {
                "button": "Home",
                "title": "Default extent"
            }
        }
    },
});