define({
    root: ({
        tooltipLabel: "Click on the map to start measure!",
        clearButtonLabel: "Clear",
        tooltipEndLabel: "Double-Click to complete Measure",
        toooltipStartLabel: "Click on the map to start measure",
        locationTooltipLabel: "Click on the map to get coordinates",
        areaTooltipLabel: "Click on the map to start measure area",
        distanceTooltipLabel: "Click on the map to start measure distance",
        NoteLabel: "Note",
        meterConLabel: "1mt = 3.28 Ft",
        hecConLabel: "1 ha = 10000 Sq mt",
        AcreConLabel: "1 Acre = 4046.9 Sq mt",
        Clear:"Clear",
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});