define({
    root: ({
        title: 'BirdTrackingPPTID',
        SensorType: "Sensor Type",
        select: "select",
        locationclasses: "locationclasses",
        PlatformID: "Platform ID",
        LocationClasses: "Location Classes",
        FromDate: "From Date",
        ToDate: "To Date",
        TimeInterval: "Time Interval",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        PleaseSelectSensorType: "Please Select Sensor Type",
        PleaseSelectBirdName: "Please Select Bird Name",
        PleaseEnterFromDate: "Please Enter From Date",
        PleaseEnterToDate: "Please Enter To Date",
        InvalidInputs: "Invalid Inputs",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater Than From Date",
        Run: "Run",
        StopOver: "Stop Over",
        ddmmyyyy: "dd - mm - yyyy",
        chkSeasonWise: "Season Wise Migration",
        Animate: "Animation",
        Density: "Density",
        Unabletofetchbirdplatformids: "Unable to fetch bird platform ids",
        NoResultFound: "No Results Found",
        UnabletofetchbirdPTTIDdetails: "Unable to fetch bird PTT ID details",
        UnabletogetAssignedids: "Unable to get Assigned ids",
        placeholderPTTID: "Select Platform ID",
        SearchText: "Enter Here",
        placeholderSensorType: "Select Sensor Type",
        BirdName: "Bird Name",
        PublicIDs:"Public IDs",
        Unabletofetchbirddetails:"Unable to fetch Bird Details",
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});