define({
    //Reports: "التقارير",
    FromDate: "من تاريخ",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    SensorType: "نوع جهاز الاستشعار",
    ToDate: "إلى تاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    FetchIDs: "جلب الرموز",
    ddmmyyyy: "سنة - شهر - يوم",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    GraphsBackgroundColor: "لون خلفية الرسوم البيانية",
    ExportReport: "إصدار تقرير",
    GenerateReports: "انشاء تقرير",
    ArgosandGPSSensorDatasummary: "Argos و GPS ، ملخص بيانات المستشعر",
    GPSGSMandArgosCounts: "Gps Gsm و Argos جمع بيانات",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    NoBirdIdsFound: 'لا يوجد رمز للطيور في الاختيار المحدد',
    UnabletoCollectbirdplatformids: "تعذر جمع رموز اجهزة الطيور.",
    Youmustcheckatleastonecheckbox: " حدد رمز الجهاز",
    SensorTypeDataReport: "تقرير بيانات نوع جهاز الاستشعار",
    IDs: "المعرف",
    Status: "الحالة الاجتماعية ",
    placeholderSensorType:"حدد نوع المستشعر",
    Inactive: "غير نشط",
    Active: "نشط",
    ReportDashBoard: "تقرير الألواح الرقمية",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    NoResultsFound: "لا توجد نتائج",
    GPSGSMandArgosDataCollection: "Gps Gsm و Argos جمع بيانات",
    PlatformIDs: "رمز الجهاز",
    TotalLocations: "عدد المواقع الكلي",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    SensorType: "نوع جهاز الاستشعار",
    SpeciesName: "النوع",
    SelectPlatformID: "رمز الجهاز",
    DurationType: "المدة",
    //DurationReport: "عدد منصة التسجيل",
    DurationReport:"عدد اجهزة التسجيل",
    TotalLocations: "عدد المواقع الكلي",
    platformid: "رمز الجهاز",
    PlatformIDs: "رمز الجهاز",
    GPSGSMandArgosDataCollection: "Gps Gsm و Argos جمع بيانات",
    placeholderSensorType: "نوع جهاز الاستشعار",
    placeholderSpeciesName: "يرجى تحديد اسم النوع",
    placeholderDurationType: "اختر نوع المدة",
    Months: "المدة بالأشهر",
    Days: "المدة بالأيام",
    Weeks: "المدة بالأسابيع",
    Locations: "الموقع",
    placeholderurationType: "اختر نوع المدة",
    UnabletofetchbirdPTTIDS: "تعذر الحصول على رمز الطيور ",
    UnabletoFetchChartDetails: "لا يمكن توفير بيانات الرسم البياني",
    //Reports: "تقرير حساب سجل النظام الأساسي",
    Reports:"عدد اجهزة التسجيل",
    PleaseSelectSpeciesName: "يرجى اختيار نوع الطير",
    placeholderPlatFormId: "حدد رمز الجهاز",
    RawData: "تصدير البيانات الأولية",
    Active: "نشط",
    Inactive: "غير نشط",
    Unabletofetchbirdnames: "تعذر الحصول على أسماء الطيور ",
    Unabletofetchbirdplatformids: "تعذر توفير رموز الطيور",
    UnabletoFetchWeekChartDetails: "تعذر جلب تفاصيل مخطط الأسبوع",
    UnabletofetchDaywiseChartDetails: "تعذر جلب تفاصيل مخطط اليوم",
    UnabletofetchMonthChartDetails: "تعذر جلب تفاصيل مخطط الشهر",
    UnabletogetAssignedids: "تعذر الحصول على  الرموز المحددة",
    UnabletoFetchRawDataDetails: "تعذر جلب تفاصيل البيانات الأولية",
    PleaseSelectDurationType: "يرجى تحديد نوع الفترة الزمنية",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
    widgets: {
        homeButton: {
            "home": {
                "button": "Home",
                "title": "Default extent"
            }
        }
    },
});