define({
    ManageDataLogs: "إدارة سجلات البيانات",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    PleaseEnterFromDate: " ادخل من تاريخ",
    PleaseEnterToDate: "إدخال حتى تاريخ",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    Submit: "تقديم",
    Clear: "مسح",
    ddmmyyyy: "سنة - شهر - يوم",
    warning: "تحذير",
    Invalid: "غير صالحة",
    NoResultsFound: "لا توجد نتائج",
    Update: "تحديث",
    SNo: "الرقم التسلسلي",
    ActivityStatus: "حالة نشطة",
    Search: "البحث:",
    Close: "قريب",
});