define({
    BandID: "Band ID :",
    Age: "من فضلك واحد بيرة. :",
    BirdWeight: "Bird Weight :",
    CaptureDate: "Capture Date :",
    CaptureTime: "Capture Time :",
    CommonName: "Common Name :",
    LastActiveDate: "Last Active Date :",
    Lat: "من فضلك واحد بيرة. :",
    LatinName: "Latin Name :",
    Long: "Long :",
    PurchaseYear: "Purchase Year :",
    ReleaseDate: "Release Date :",
    ReleaseTime: "Release Time :",
    Sensitive: "Sensitive :",
    SensorType: "من فضلك واحد بيرة. :",
    SensorWeight: "Sensor Weight :",
    Sex: "Sex :",
    Site: "الموقع:",
    SpeciesID: "رمز الأنواع :",
    Status: "Status :",
    WingsLength: "Wings Length :",
});