define({
    root: ({
        MMC: "MMC Report",
        PlatformID: "PTT ID",
        MigrationStartDate: "Migration Start Date",
        MigrationEndDate: "Migration End Date",
        Duration: "Duration (Days)",
        AverageSpeed: "Average Speed (Kt)",
        AverageAltitude: "Average Altitude (Meter)",
        Distance: "Distance (Km)",
        Locations:"Locations",
        ReportDashBoard:"Report Dashboard",
        SpeciesName: "Species",
        SensorType: "Sensor Type",
        FromDate: "From Date",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        ToDate: "To Date",
        FetchIDs: "Fetch IDs",
        GenerateMMC: "Generate MMC",
        MovementMetricCalculations: "Movement Metric Calculations",
        PleaseSelectSpeciesName: "Select Species Name",
        PleaseSelectPlatformId: "Select Platform Id",
        PleaseSelectSensorType: "Select Sensor Type",
        placeholderPlatFormId: "Select Platform ID",
        placeholderSensorType: "Select Sensor",
        placeholderSpeciesName:"Select Species",
        WinteringArea: "Wintering Duration",
        SpringMigration: "Spring Migration",
        ddmmyyyy:"dd - mm - yyyy",
        BreedingArea: "Summering Duration",
        AutumnMigration: "Autumn Migration",
        ExportReport: "Export Report",
        PleaseEnterFromDate: "Enter From Date",
        PleaseEnterToDate: "Enter To Date",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater than From Date",
        ddmmyyyy: "dd-mm-yyyy ",
        PlatformID: "Platform ID",
        Unabletofetchbirdnames: "Unable to fetch bird names",
        Unabletofetchplatformids: "Unable to fetch platform ids",
        UnabletofetchbirdPTTIDdetails:"Unable to fetch bird PTT ID details",
        NoResultFound: "No Result Found",
        Unabletofetchmmcreportdetails: "Unable to fetch MMC Report details",
        placeholderSpeciesName: "Select Species",
        placeholderSensorType: "Select Sensor",
        Errortryagain: "Error, try again",
        Speed: "Average Speed (Kt)",
        Altitude: "Average Altitude (Meter)",
        ArrivalDate: "Arrival Date",
        DepartureDate: "Departure Date",
        Active: "Active",
        Inactive: "Inactive",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
        ErrorinUpdate: "Error in Update",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});