define({
    root: ({
        ManageDataLogs: "Manage Data Logs",
        FromDate: "From Date",
        ToDate: "To Date",
        PleaseEnterFromDate: "Enter From Date",
        PleaseEnterToDate: "Enter To Date",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater than From Date",
        Submit: "Submit",
        Clear: "Clear",
        ddmmyyyy:"dd - mm - yyyy",
        warning: "warning",
        Invalid: "Invalid",
        NoResultsFound: "No Results Found",
        Unabletofetchbirdids: "Unable to fetch bird ids",
        error: "error",
        Error: "Error",
        success: "success",
        Success: "Success",
        SelectBirdIds: "Select Bird Ids",
        UnabletoCreateUser: "Unable to Create User",
        assignBirds: "Assign Birds",
        SelectBird: "Select Assign Birds",
        Update: "Update",
        SNo: "SNo",
        ActivityStatus: "Activity Status",
        Search: "Search:",
        Close:"Close",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});