define({
   
        title: "birdTrackingBynames",
    SpeciesName: "الأنواع",
    SensorCategory: "فئة المستشعر",
    SensorType: "نوع جهاز الاستشعار",
    Year: "السنة ",
    TimeInterval: "الفترة الزمنية",
    PlatFormID: "قائمة رموز الأجهزة",
    All:"الجميع",
        Select: "Select",
    Main: "رئيسي",
    Secondary: "ثانوي",
    PleaseSelectSpeciesName: "اختر نوع الطير",
    PleaseSelectSensorCategory: "اختر فئة المستشعر",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    PleaseSelectYear: "حددد السنة",
    PleaseSelectTimeInterval: "حدد الفاصل الزمني",
    PleaseSelectPlatformID: " حدد رمز الجهاز",
    Run: "تشغيل",
    Animate: "تحريك",
    StopOver: "نقطة توقف",
    chkSeasonWise: "الهجرة الموسمية",
    Unabletofetchbirdnames: "تعذر الحصول على أسماء الطيور",
    UnabletofetchBirdSensorTypes: "تعذر تحديد نوع جهاز الاستشعار بالطائر",
    UnabletofetchBirdYears: "تعذر تحديد عمر الطائر",
    UnabletofetchBirdPlatformIds: "تعذر توفير رموز الطيور",
    NoResultFound: "لا توجد نتائج",
    UnabletofetchBirdNamesDetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    placeholderSpeciesName: "اختر نوع الطير",
    placeholderYear: "حددد السنة",
    placeholderSensorType: "حدد نوع المستشعر",
    placeholderSensorCategory:"حدد فئة المستشعر",
    placeholderPlatFormId: "تحديد رمز الجهاز",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    Active: "نشط",
    Inactive: "غير نشط",
    NoDataFound: "عدد السجلات كبير جداً ، يرجى تحديد الفترة الزمنية لتقليل البيانات.",
    HugeData: "بيانات ضخمة. الرجاء تحديد خيارات التصفية",
    MigrationNote: "ملاحظة: قد يتكرر مؤشر اللون بحسب موسم الهجرة ",
    TIhours: "ساعات",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد"
});