define({

    title: 'BirdTrackingPPTID',
    ddmmyyyy: "سنة - شهر - يوم",
    SensorType: "نوع جهاز الاستشعار",
    select: "select",
    locationclasses: "تصنيف الموقع",
    PlatformID: "رمز الجهاز",
    LocationClasses: "تصنيف الموقع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    TimeInterval: "الفترة الزمنية",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    PleaseSelectPlatformID: "تحديد رمز الجهاز",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    InvalidInputs: "مدخلات غير صحيحة",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    ToTimeShouldbeGreaterthanFromTime: '"الفترة من" يجب أن تكون أكبر من "الفترة إلى "',
    ToDateLocationTitle: "حدد النقطة على الخريطة لملء إلى تاريخ و إلى وقت",
    FromDateLocationTitle: "حدد النقطة على الخريطة لملء من تاريخ و من وقت",
    Run: "تشغيل",
    StopOver: "نقطة توقف",
    chkSeasonWise: "الهجرة الموسمية  ",
    Animate: "الحركة",
    Density: "كثافة النقطة",
    Unabletofetchbirdplatformids: "تعذر توفير رموز الطيور",
    NoResultFound: "لا توجد نتائج",
    UnabletofetchbirdPTTIDdetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    UnabletogetAssignedids: "تعذر الحصول على  الرموز المحددة",
    placeholderPTTID: "تحديد رمز الجهاز",
    placeholderSensorType: " حدد نوع المستشعر",
    placeholderMigrationType: "اختر الموسم",
    MigrationType: "الموسم",
    update: "تحديث",
    EnterTime: "أدخل الوقت",
    Time: "الوقت",
    PleaseSelectMigration: "اختر الموسم",
    PleaseEnterTime: "أدخل الوقت",
    ResultsUpdated: "تم تحديث بيانات الموسم",
    ResultsNotUpdated: "تعذر تحديث بيانات الموسم",
    UnabletofetchSeasonCorrectionDetails: "تعذر جلب تفاصيل تصحيح الموسم",
    selectcorrectPoint: "حدد النقطة الصحيحة للتحديث",
    winter: "الشتاء",
    spring: "الربيع",
    autumn: "الخريف",
    summer: "الصيف",
    SelectedItems: "محدد"
});