define({

    title: 'BirdTrackingPPTID',
    ddmmyyyy: "سنة - شهر - يوم",
    SensorType: "نوع جهاز الاستشعار",
    select: "select",
    locationclasses: "تصنيف الموقع",
    PlatformID: "رمز الجهاز",
    LocationClasses: "تصنيف الموقع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    TimeInterval: "الفترة الزمنية",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    PleaseSelectBirdName: "يرجى تحديد معرّف المنصة",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    InvalidInputs: "مدخلات غير صحيحة",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    Run: "تشغيل",
    StopOver: "نقطة توقف",
    chkSeasonWise: "الهجرة الموسمية  ",
    Animate: "الحركة",
    Density: "كثافة النقطة",
    Unabletofetchbirdplatformids: "تعذر توفير رموز الطيور",
    NoResultFound: "لا توجد نتائج",
    UnabletofetchbirdPTTIDdetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    UnabletogetAssignedids: "تعذر الحصول على  الرموز المحددة",
    placeholderPTTID: " حدد رمز الجهاز",
    placeholderSensorType: " حدد نوع المستشعر",
    BirdName: "اسم الطائر",
    PublicIDs: "المعرفات العامة",
    Unabletofetchbirddetails: "تعذر الحصول على تفاصيل معرفات الطيور",
});