define({
    AddBird: "إضافة طائر",
    PlatformID: "رمز الجهاز",
    PlatformWeight: "وزن الجهاز",
    CaptureDate: "تاريخ الالتقاط",
    CaptureTime: "وقت الالتقاط",
    Latitude: "خط العرض",
    Longitude: "خط الطول",
    SensorType: "نوع جهاز الاستشعار",
    EnterValidyearFutureYearsarenotallowed: "أدخل سنة صالحة والسنوات المقبلة غير مسموح بها",
    Site: "الموقع",
    Species: "النوع",
    Age: "العمر",
    Sex: "الجنس",
    Status: "الحالة الاجتماعية ",
    Lastactivedate: "تاريخ آخر نشاط",
    AC: "نشط",
    NA: "غير نشط",
    //Argos: "نظام ارجوس لتحديد المواقع (ARGOS)",
    //GPS: " (GPS)  النظام العالمي لتحديد المواقع ",
    //GSM: "النظام العالمي للاتصالات المتنقلة (GSM)",

    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    Weight: "الوزن",
    Wings: "أجنحة",
    BandID: "رمز النطاق",
    LastActiveDate: "تاريخ آخر نشاط",
    RelDate: "تاريخ الإطلاق",
    RelTime: "وقت الإطلاق",
    Purchaseyear: "سنة الشراء",
    PurchaseYear: "سنة الشراء",
    Bill: "مشروع قانون",
    Tarsus: "طرسوس",
    Notes: "ملاحظات",
    Update: "تحديث",
    Clear: "مسح",
    Save: "حفظ",
    BirdsInfo: "معلومات الطيور",
    AddBird: "إضافة طائر",
    EditUpdate: "تحرير / تحديث",
    Site: "الموقع",
    EnterPlatformID: "أدخل رمز الجهاز",
    SelectType: "اختر النوع",
    UpdateBird: "تحديث بيانات الطائر",
    SaveandUpdate: "حفظ وتحديث",
    MarkedFeildsareMandatory: "الحقول المحددة إلزامية",
    EnterPlatformID: "أدخل رمز الجهاز",
    EnterWeight: "أدخل الوزن",
    EnterCaptureDate: "أدخل تاريخ الالتقاط",
    EnterCaptureTime: "أدخل وقت الالتقاط",
    EnterLatitude: "أدخل خط العرض",
    EnterLongtitude: "أدخل خط الطول",
    SelectType: "اختر النوع",
    Selectsite: "حدد الموقع",
    SelectSpecies: "حدد النوع",
    SelectAge: "حدد العمر",
    SelectSex: "حدد الجنس",
    EnterWeight: "أدخل الوزن",
    EnterWings: "أدخل الأجنحة",
    EnterBandID: "أدخل رمز النطاق",
    SelectStatus: "حدد الحالة",
    EnterActiveDate: "أدخل تاريخ النشاط",
    EnterReleaseDate: "يُرجى إدخال تاريخ الإطلاق",
    EnterDate: "أدخل التاريخ",
    EnterTime: "أدخل الوقت",
    EnterYear: "أدخل السنة",
    EnterTarsus: "أدخل طرسوس",
    EnterNotes: "أدخل الملاحظات",
    EnterBill: "أدخل الفاتورة",
    PleaseEnterPlatformID: "أدخل رمز الجهاز",
    Unabletofetchbirdids: "تعذر توفير رموز الطيور",
    RecordisAddedSuccessfully: "تمت إضافة السجل",
    RecordisUpdatedSuccessfully: "تم تحديث السجل ",
    UnabletoFetchAgeCodes: "تعذر الحصول على كود عُمر الطائر",
    UnabletoFetchSexCodes: "تعذر الحصول على كود جنس الطائر",
    UnabletoFetchSpecies: "تعذر الحصول على هذا النوع",
    BirdName: "اسم الطائر",
    EnterBirdName: "أدخل اسم الطائر",
    SeconadrySensorType: "ثانوي",
    PlatformIDAlreadyExist: "معرف النظام الأساسي موجود بالفعل",
    PlatformID: "رمز الجهاز",
    PlatformWeight: "وزن الجهاز",
    CaptureDate: "تاريخ الالتقاط",
    CaptureTime: "وقت الالتقاط",
    Latitude: "خط العرض",
    Longitude: "خط الطول",
    SensorType: "نوع جهاز الاستشعار",
    Site: "الموقع",
    Species: "النوع",
    Age: "العمر",
    Sex: "الجنس",
    Status: "الحالة الاجتماعية ",
    Lastactivedate: "تاريخ آخر نشاط",
    AC: "نشط",
    NA: "غير نشط",
    Migration: "الهجرة",
    Residential: "سكني",
    Dispersal: "تشتيت انتشار",
    SelectMigration: "حدد الهجرة",
    BirdName: "اسم الطائر",
    EnterBirdName: "أدخل اسم الطائر",
    SeconadrySensorType: "ثانوي",
    MigrationType: "نوع الترحيل",
    PlatformIDAlreadyExist: "معرف النظام الأساسي موجود بالفعل",
    //Argos: "نظام ارجوس لتحديد المواقع (ARGOS)",
    //GPS: " (GPS)  النظام العالمي لتحديد المواقع ",
    //GSM: "النظام العالمي للاتصالات المتنقلة (GSM)",

    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    Weight: "الوزن",
    Wings: "أجنحة",
    BandID: "رمز النطاق",
    Status: "الحالة الاجتماعية ",
    LastActiveDate: "تاريخ آخر نشاط",
    RelDate: "تاريخ الإصدار",
    RelTime: "وقت الارتباط",
    Purchaseyear: "سنة الشراء",
    Bill: "الفاتورة",
    Tarsus: "رسغ القدم",
    Notes: "ملاحظات",
    Update: "تحديث",
    Clear: "مسح",
    Save: "حفظ",
    BirdsInfo: "معلومات الطيور",
    AddBird: "إضافة طائر",
    EditUpdate: "تحرير / تحديث",
    Site: "الموقع",
    EnterPlatformID: "أدخل رمز الجهاز",
    SelectType: "اختر النوع",
    UpdateBird: "تحديث بيانات الطائر",
    SaveandUpdate: "حفظ وتحديث",
    MarkedFeildsareMandatory: "الحقول المحددة إلزامية",
    EnterPlatformID: "أدخل رمز الجهاز",
    EnterWeight: "أدخل الوزن",
    EnterCaptureDate: "أدخل تاريخ الالتقاط",
    EnterCaptureTime: "أدخل وقت الالتقاط",
    EnterLatitude: "أدخل خط العرض",
    EnterLongtitude: "أدخل خط الطول",
    SelectType: "اختر النوع",
    Selectsite: "حدد موقع",
    SelectSpecies: "حدد النوع",
    SelectAge: "حدد العمر",
    SelectSex: "حدد الجنس",
    EnterWeight: "أدخل الوزن",
    EnterWings: "أدخل الأجنحة",
    EnterBandID: "أدخل رمز النطاق",
    SelectStatus: "حدد الحالة",
    EnterActiveDate: "أدخل تاريخ النشاط",
    EnterReleaseDate: "يُرجى إدخال تاريخ الإطلاق",
    EnterDate: "أدخل التاريخ",
    EnterTime: "أدخل الوقت",
    EnterYear: "أدخل السنة",
    EnterTarsus: "أدخل رسغ القدم",
    EnterNotes: "أدخل الملاحظات",
    EnterBill: "أدخل الفاتورة",
    PleaseEnterPlatformID: "أدخل رمز الجهاز",
    Unabletofetchbirdids: "تعذر توفير رموز الطيور",
    RecordisAddedSuccessfully: "تمت إضافة السجل",
    RecordisUpdatedSuccessfully: "تم تحديث السجل ",
    UnabletoFetchAgeCodes: "تعذر الحصول على كود عُمر الطائر",
    UnabletoFetchSexCodes: "تعذر الحصول على كود جنس الطائر",
    UnabletoFetchSpecies: "تعذر الحصول على هذا النوع",
    BirdName: "اسم الطائر",
    EnterBirdName: "أدخل اسم الطائر",
    SeconadrySensorType: "ثانوي",
    PlatformIDAlreadyExist: "معرف النظام الأساسي موجود بالفعل",
    Migration: "الهجرة",
    Residential: "سكني",
    Dispersal: "تشتيت انتشار",
    SelectMigration: "حدد الهجرة",
    MigrationType: "نوع الترحيل",
    birdnamealreadyexists: "اسم الطائر موجود مسبقا",
    capdatelabel: "تاريخ الإمساك يجب يكون قبل تاريخ الاطلاق",
    EntervalidPurchaseYear: "ادخل تاريخ الشراء ",
    EntervalidLatitude: "ادخل خط الطول ",
    EntervalidLongitude: "ادخل خط العرض",
    FutureYearsarenotallowed: "السنوات القادمة غير مسموح بها",
    ErrorinUpdate:"خطأ في التحديث",

    Close: "قريب",
    widgets: {
        homeButton: {
            "home": {
                "button": "Home",
                "title": "Default extent"
            }
        }
    },
});