define({
    root: ({
        Reports:"Platform Record Count",
        FromDate: "From Date",
        PleaseEnterFromDate: "Enter From Date",
        ToDate:"To Date",
        PleaseEnterToDate: "Enter To Date",
        FetchIDs: "Fetch IDs",
        Reports: "Platform Record Count Report",
        Argos: "Argos",
        GPS: "GPS",
        GSM:"GSM",
        GPSandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        GraphsBackgroundColor: "Graphs Background Colour",
        ExportReport:"Export Reports",
        GenerateReports: "Generate Report",
        ArgosandGPSSensorDatasummary: "GPS,GSM and Argos Sensor Data Summary",
        GPSGSMandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        ToDateShouldbeGreaterthanFromDate:"To Date Should be Greater than From Date",
        PleaseSelectIDS: "Select IDS",
        ddmmyyyy: "dd - mm - yyyy ",
        NoBirdIdsFound: 'No Platform Ids found for the given selection.',
        UnabletoCollectbirdplatformids: "Unable to Collect bird platform ids.",
        PleaseSelectSensorType: "Select Sensor Type",
        placeholderSensorType:"Select Sensor",
        SensorType: "Sensor Type",
        SensorTypeDataReport: "Sensor Type Data Report",
        Youmustcheckatleastonecheckbox: "Select Platform id",
        warning: "warning",
        Invalid: "Invalid",
        PleaseSelectIds: "Select Id's",
        IDs: "IDs",
        Status: "Status",
        Inactive: "Inactive",
        Active: "Active",
        ReportDashBoard: "Report Dashboard",
        NoResultsFound: "No Results Found",
        GPSGSMandArgosDataCollection: "Sensor Type Data Collection",
        PlatformIDs: "Platform ID's",
        TotalLocations:"Total Locations",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        SensorType: "Sensor Type",
        SpeciesName: "Species",
        SelectPlatformID: "Platform ID",
        DurationType: "Duration",
        DurationReport: "Platform Record Count",
        TotalLocations: "Total Locations",
        platformid: "platform ID",
        PlatformIDs: "Platform IDs",
        GPSGSMandArgosDataCollection: "GPS GSM and Argos Data Collection",
        placeholderSensorType:"Select Sensor",
        placeholderSpeciesName: "Select Species",
        placeholderDurationType: "Select Duration",
        Months: "Duration by Months",
        Days: "Duration by Days",
        Weeks:"Duration by Weeks",
        Locations: "Locations",
        placeholderurationType: "Select Duration Type",
        UnabletofetchbirdPTTIDS: "Unable to fetch bird PTT IDS",
        UnabletoFetchChartDetails: "Unable to Fetch Chart Details",
        PleaseSelectSpeciesName: "Select SpeciesName",
        placeholderPlatFormId: "Select Platform ID",
        RawData: "Export Raw Data",
        Active: "Active",
        Inactive: "Inactive",
        Unabletofetchbirdnames: "Unable to fetch Bird Names",
        Unabletofetchbirdplatformids: "Unable to fetch Platformids",
        UnabletoFetchWeekChartDetails: "Unable to fetch Week Chart Details",
        UnabletofetchDaywiseChartDetails: "Unable to fetch Day Chart Details",
        UnabletofetchMonthChartDetails: "Unable to fetch Month Chart Details",
        UnabletogetAssignedids: "Unable to get Assigned ids",
        UnabletoFetchRawDataDetails: "Unable to Fetch Raw Data Details",
        PleaseSelectDurationType: "Select Duration Type",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});