define({
    title: 'BirdTrackingPPTID',
    locationclasses: "تصنيف الموقع",
    PlatformID: "رمز الجهاز",
    durationTime: "الفترة الزمنية",
    LocationClasses: "تصنيف الموقع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    TimeInterval: "الفترة الزمنية",
    onemonth: "1 شهور",
    Previousmonths: "6 شهور",
    oneyear: "سنة",
    twoyears: "سنتان",
    PleaseselectPlatformID: "حدد رمز الجهاز",
    PleaseselectDurationTime: "يرجى اختيار الوقت المستغرق",
    TrackingBirdID: "تشغيل",
    NoResultsFound: "لا توجد نتائج",
    UnabletofetchbirdPTTIDdetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    placeholderPTTID: " حدد رمز الجهاز",
    Animation: "تحريك",
    placeholderDurationTime: "حدد المدة",
    SelectBirdName: "اسم الطائر",
    PleaseselectBirdName: "اختر الطير",
    placeholderBirdName: "حدد اسم الطائر",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد"
});