define({
    root: ({
        title: 'BirdTrackingPPTID',
        SensorType: "Sensor Type",
        select: "select",
        locationclasses: "locationclasses",
        PlatformID: "Platform ID",
        LocationClasses: "Location Classes",
        FromDate: "From Date",
        ToDate: "To Date",
        TimeInterval: "Time Interval",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        PleaseSelectSensorType: "Select Sensor Type",
        PleaseSelectPlatformID: "Select Platform ID",
        PleaseEnterFromDate: "Enter From Date",
        PleaseEnterToDate: "Enter To Date",
        InvalidInputs: "Invalid Inputs",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater Than From Date",
        ToTimeShouldbeGreaterthanFromTime: "To Time Should be Greater Than From Time",
        ToDateLocationTitle: "Select the point from map to fill the ToDate and ToTime",
        FromDateLocationTitle: "Select the point from map to fill the FromDate and FromTime",
        Run: "Run",
        StopOver: "Stop Over",
        ddmmyyyy: "dd - mm - yyyy",
        chkSeasonWise: "Season Wise Migration",
        Animate: "Animation",
        Density: "Density",
        Unabletofetchbirdplatformids: "Unable to fetch Platform ids",
        NoResultFound: "No Results Found",
        UnabletofetchbirdPTTIDdetails: "Unable to fetch bird PTT ID details",
        UnabletogetAssignedids: "Unable to get Assigned ids",
        placeholderPTTID: "Select Platform ID",
        SearchText: "Enter Here",
        placeholderSensorType: "Select Sensor Type",
        placeholderMigrationType:"Select Season",
        MigrationType:"Season",
        update: "Update",
        EnterTime: "Enter Time",
        Time: "Time",
        PleaseSelectMigration: "Select Season",
        PleaseEnterTime: "Enter Time",
        ResultsUpdated: "Season Data Updated",
        ResultsNotUpdated: "Unable to Update Season Data",
        UnabletofetchSeasonCorrectionDetails: "Unable to fetch Season Correction Details",
        selectcorrectPoint: "Select the valid point to update",
        winter: "Wintering",
        spring:"Spring",
        autumn:"Autumn",
        summer: "Summering",
        SelectedItems: "Selected"
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});