define({
    root: ({
        SpeciesStatus: "Species Status",
        All: "All",
        Active: "Active",
        NonActive: "Non Active",
        TrackingPeriod: "Tracking Period",
        FromDate: "From Date",
        ToDate: "To Date",
        CollectSpeciesInformation: "Collect Species Information",
        Whole: "Whole",
        Within: "Within",
        PID: "PID",
        Sensor: "Sensor Type",
        Species: "Species",
        FromDate: "From Date",
        ToDate: "To Date",
        Loc: "Loc",
        Interval: "Interval",
        Actions: "Actions",
        StopOver: "Stop  Over",
        PleaseEnterFromDate: "Please Enter From Date",
        PleaseEnterToDate: "Please Enter To Date",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater than From Date",
        PleaseSelectSpeciesStatus: "Please Select Species Status",
        chkSeasonWise: "Season Wise Migration",
        ddmmyyyy: "dd - mm - yyyy",
        placeholderSelectStatus:"Select Status",
        PointDensity:"PointDensity",
        MCP: "MCP",
        SelectedMCP:"Selected Points MCP",
        PointDensity: "Point Density",
        Run: "Run",
        Animate: "Animate",
        checked: "checked",
        unchecked: "un checked",
        DeleteFromMap: "Delete From Map",
        DeleteFromDatabase:"Delete From Database",
        NoResultFound: "No Result Found",
        TotalLength: "Total Length",
        plotoneBirdonthemap: "Plot only one Species on the map to get MCP",
        NoDatafound: "No.of records exceed the memory, please increase the time interval to reduce the data.",
        ClearData: "No.of records exceed the memory, please clear the plotted Data.",
        all: "All",
        active: "Active",
        nonactive:"Non Active",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});