define({
    root: ({
        AddBird: "Add Bird",
        PlatformID: "Platform ID",
        PlatformWeight: "Platform Weight",
        CaptureDate: "Capture Date",
        CaptureTime: "Capture Time",
        EnterValidyearFutureYearsarenotallowed:"Enter Valid year & Future Years are not allowed",
        Latitude: "Latitude",
        Longtitude: "Longtitude",
        SensorType: "Sensor Type",
        Site:"Site",
        Species: "Species",
        Age: "Age",
        Sex: "Sex",
        Status: "Status",
        AC: "Active",
        NA: "InActive",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        Weight: "Weight",
        Wings: "Wings",
        BandID: "Band ID",
        LastActiveDate: "Last Active Date",
        Lastactivedate: "Last Active Date",
        RelDate: "Release Date",
        RelTime: "Release Time",
        PurchaseYear: "Purchase Year",
        Bill: "Bill",
        Tarsus: "Tarsus",
        Notes: "Notes",
        Update: "Update",
        Clear: "Clear",
        Save: "Save",
        BirdsInfo: "Bird's Info",
        AddBird: "Add Bird",
        EditUpdate: "Edit/Update",
        UpdateBird:"Update Bird",
        SaveandUpdate: "Save and Update",
        MarkedFeildsareMandatory:"Marked Fields are Mandatory",
        EnterPlatformID: "Enter Platform ID",
        EnterWeight: "Enter Weight",
        EnterCaptureDate: "Enter Capture Date",
        EnterCaptureTime: "Enter Capture Time",
        EnterLatitude: "Enter Latitude",
        EnterLongtitude: "Enter Longtitude",
        SelectType: "Select Type",
        Selectsite: "Select site",
        SelectSpecies: "Select Species",
        SelectAge: "Select Age",
        SelectSex: "Select Sex",
        EnterWeight: "Enter Weight",
        EnterWings: "Enter Wings",
        EnterBandID: "Enter Band ID",
        SelectStatus: "Select Status",
        EnterActiveDate: "Enter Active Date",
        EnterDate: "Enter Date",
        EnterTime: "Enter Time",
        EnterYear: "Enter Year",
        EnterTarsus: "Enter Tarsus",
        EnterNotes: "Enter Notes",
        EnterBill: "Enter Bill",
        PleaseEnterPlatformID: "Enter Platform ID",
        ddmmyyyy: "dd-mm-yyyy",
        EnterReleaseDate:"Enter Release Date",
        BirdName: "Bird Name",
        EnterBirdName: "Enter Bird Name",
        SeconadrySensorType: "Secondary",
        PlatformIDAlreadyExist: "Platform ID already exist",
        Migration: "Migration",
        Residential: "Residential",
        Dispersal: "Dispersal",
        SelectMigration: "Select Migration",
        MigrationType: "Migration Type",
        birdnamealreadyexists: "Bird name already exists",
        capdatelabel: "Capture Date Should be less than Release Date",
        EntervalidPurchaseYear: "Enter valid PurchaseYear",
        EntervalidLatitude: "Enter valid Latitude",
        EntervalidLongitude: "Enter valid Longitude",
        ErrorinUpdate:"Error in Update",










        PlatformID: "Platform ID",
        PlatformWeight: "Platform Weight",
        CaptureDate: "Capture Date",
        CaptureTime: "Capture Time",
        Latitude: "Latitude",
        Longitude: "Longitude",
        SensorType: "Sensor Type",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        Species: "Species",
        Age: "Age",
        Sex: "Sex",
        Weight: "Weight",
        Wings: "Wings",
        BandID: "Band ID",
        Status: "Status",
        AC: "Active",
        NA: "InActive",
        Lastactivedate: "Last Active Date",
        RelDate: "Release Date",
        RelTime: "Release Time",
        Purchaseyear: "Purchase year",
        Bill: "Bill",
        Tarsus: "Tarsus",
        Notes:"Notes",
        Add: "Add",
        Update: "Update",
        Clear: "Clear",
        EnterPlatformID: "Enter Platform ID",
        Unabletofetchbirdids: "Unable to fetch bird ids",
        RecordisAddedSuccessfully: "Record is Added Successfully",
        RecordisUpdatedSuccessfully: "Record is Updated Successfully",
        UnabletoFetchAgeCodes: "Unable to Fetch AgeCodes",
        UnabletoFetchSexCodes: "Unable to Fetch SexCodes",
        UnabletoFetchSpecies: "Unable to Fetch Species",
        SeconadrySensorType:"Secondary",
        PlatformIDAlreadyExist: "Platform ID already exist",
        Migration: "Migration",
        Residential: "Residential",
        Dispersal: "Dispersal",
        SelectMigration: "Select Migration",
        MigrationType: "Migration Type",
        Close: "Close",
        FutureYearsarenotallowed:"Future Years are not allowed",

        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});