define({
    Temperature:"البيانات",
    languageLabel: "عربي",
    DataLabel: "البيانات",
    PTTIDs: "رمز الجهاز",
    IDs: "الرموز",
    DataNames: "الأسماء",
    /*DataNames: "أسماء ",*/
    StopOver: "نقطة توقف",
    MCP:"MCP",
    Tools: "الأدوات",
    Reports: "التقارير",
    Print: "الطباعة",
    DataSummary: "ملخص البيانات",
    BirdsInfo: "معلومات الطيور",
    BirdTrackingInformationSystem: "نظام معلومات تتبع الطيور",
    Help: "مساعدة",
    BirdTracking:"تتبع الطيور",
    Logout:"تسجيل خروج",
    DataBrowsebyPTTIDs: "تصفح عن طريق الرمز",
    QueryResults: "نتيجة البحث",
    StopoverResults: "نتائج نقطة التوقف",
    MovementMetricCalculations: "حسابات قياس الحركة",
    ExporttoExcel: "تصدير إلى إكسل",
    ExporttoShapes: "تصدير الى Shapefile",
    QueryResults: "نتيجة البحث",
    StopOverResults: "نتائج نقطة التوقف",
    Pointdeletedsuccessfully: "تم الحذف ",
    Layers: "الطبقات",
    Start:"يبدأ",
    Stop: "إيقاف ",
    BirdInfo: "معلومات الطيور",
    ExportVideo: "تصدير الفيديو",
    Exportvideo: "تصدير الفيديو",
    ClearGraphics: "مسح الرسومات",
    Measurement: "القياس",
    BaseMaps: "خريطة الأساس",
    ManageBirds: "إدارة الطيور",
    ManageUsers: "ادارة المستخدمين",
    Reports: "التقارير",
    //Manage: "إدارة",
    Manage: "إدارة",
    Youmustcheckatleastonecheckbox: "حدد رمز الجهاز",
    Areyousuretoclearthegraphics: "هل أنت متأكد من مسح هذه الرسومات؟",
    DataBrowsebyNames: "تصفح بالأسماء",
    DataBrowsebyIDs: "تصفح حسب الرموز",
    Animate: "تحريك",
    ExternalDataset: "مجموعة البيانات الخارجية",
    Reports: "التقارير",
    SensorTypeDataReport: "تقرير بيانات نوع جهاز الاستشعار",
    SensorTypeDataReport: "تقرير بيانات نوع جهاز الاستشعار",
    Explore: "يكتشف",
    LocationClassesReports: "تقارير فئات الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    DataSummary: "ملخص البيانات",
    DataSummaryReport: "تقرير ملخص البيانات",
    MMCReport: "تقرير MMC",
    ManageDataLogs: "إدارة سجلات البيانات",
    AssignBirdsToPublic: "تعيين طيور للجمهور",
    Yes: "نعم",
    No: "لا",
    Home: "الصفحة الرئيسية",
    TestLinkForReports: "اختبار الارتباط بالتقارير",
    Reports: "التقارير",
    TotalLocations: "إجمالي المواقع",
    DurationReport: "عدد اجهزة التسجيل",
    TrackingReport: "تقرير التتبع",
    ExploreReport: "تصفح التقرير",
    ARGOS: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    UpdateMigration: "تصحيح الموسم",
    Close: "قريب",
    EnterFileName: "أدخل اسم الملف :",
    Cancel: "الغاء",
    OK:"نعم",
    /*Locations: "المواقع"*/
    Locations: "موقع"
});