define({
    BandID: "Band ID :",
    Age: "Age :",
    BirdWeight: "Bird Weight :",
    CaptureDate: "Capture Date :",
    CaptureTime: "Capture Time :",
    CommonName: "Common Name :",
    LastActiveDate: "Last Active Date :",
    Lat: "Lat :",
    LatinName: "Latin Name :",
    Long: "Long :",
    PurchaseYear: "Purchase Year :",
    ReleaseDate: "Release Date :",
    ReleaseTime: "Release Time :",
    Sensitive: "Sensitive :",
    SensorType: "Sensor Type :",
    SensorWeight: "Sensor Weight :",
    Sex: "Sex :",
    Site: "الموقع:",
    SpeciesID: "Species ID :",
    Status: "Status :",
    WingsLength: "Wings Length :",
    hello: "hello",
    Unabletodeletethepoint: "لم يتم الحذف",
    Pointdeletedsuccessfully: "تم الحذف ",
    TotalLength: ": الطول الإجمالي",
    Kilometers: "كيلومترات",
    Meters: "Meters",
    NoMigration: "لا هجرة",
    WinterDuration: "مدة الشتاء",
    SpringMigration: "هجرة الربيع",
    BreedingDuration: "مدة الصيف",
    AutumnMigration: "هجرة الخريف",
});