define({
    root: ({
        Reports:"Reports",
        FromDate: "From Date",
        PleaseEnterFromDate: "Enter From Date",
        ToDate:"To Date",
        PleaseEnterToDate: "Enter To Date",
        FetchIDs: "Fetch IDs",
        Reports: "Reports",
        Argos: "Argos",
        GPS: "GPS",
        GSM:"GSM",
        GPSandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        GraphsBackgroundColor: "Graphs Background Colour",
        ExportReport:"Export Reports",
        GenerateReport: "Generate Report",
        ArgosandGPSSensorDatasummary: "GPS,GSM and Argos Sensor Data Summary",
        GPSGSMandArgosCounts: "GPS,GSM and Argos Counts",
        LocationClasses: "Location Classes",
        GPSLocationsTable: "GPS Locations Table",
        ToDateShouldbeGreaterthanFromDate:"To Date Should be Greater than From Date",
        PleaseSelectIDS: "Select IDS",
        ddmmyyyy: "dd - mm - yyyy ",
        NoBirdIdsFound: 'No Platform Ids found for the given selection.',
        UnabletoCollectbirdplatformids: "Unable to Collect bird platform ids.",
        PleaseSelectSensorType: "Select Sensor Type",
        placeholderSensorType:"Select Sensor",
        SensorType: "Sensor Type",
        SensorTypeDataReport: "Sensor Type Data Report",
        Youmustcheckatleastonecheckbox: "Select Platform id",
        warning: "warning",
        Invalid: "Invalid",
        PleaseSelectIds: "Select Id's",
        IDs: "IDs",
        Status: "Status",
        Inactive: "Inactive",
        Active: "Active",
        ReportDashBoard: "Report Dashboard",
        NoResultsFound: "No Results Found",
        GPSGSMandArgosDataCollection: "Sensor Type Data Collection",
        PlatformIDs: "Platform ID",
        TotalLocations:"Locations",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        ARGOSReport: "ARGOS Reprot",
        SpeciesName: "Species",
        SelectPlatformID: "Select Platform ID",
        NumberofLocations:"Number of Locations",
        NumberofSpecies: "Number of Species",
        NumberofBirds: "Number of Birds",
        AverageSpeed: "Average Speed (Kt)",
        AverageAltitude: "Average Altitude (Meter)",
        TotallocationsCountChart: "Total locations year wise",
        TotallocationsChart: "Total locations",
        ViewReport: "View Report",
        AverageSpeedChart: "Location Classes",
        AverageAltitudeChart:"Altitude",
        TotalLocationsforSelectedIDs: "Total Locations year wise",
        LocationsCountforSelectedIDs:"Total Locations",
        FlightSpeedofSelectedPTTIDs: "Flight Speed",
        AltitudeofSelectedPTTIDs: "Altitude",
        ReportWithArgosIDs: "Report With ARGOS IDs",
        LocationClassesReport: "Location Classes",
        RawData: "Export Raw Data",
        UnabletoFetchChartDetails: "Unable to Fetch Chart Details",
        Locations: "Locations",
        Speed: "Speed (Kt)",
        UnabletofetchbirdPTTIDS: "Unable to fetch bird PTT IDS",
        UnabletofetchBirdsLocation: "Unable to fetch Birds Location",
        UnabletofetchTotalBirds: "Unable to fetch Total Birds",
        UnabletofetchTotalSpecies: "Unable to fetch Total Species",
        UnabletofetchAvgSpeed: "Unable to fetch Avg Speed",
        UnabletofetchAverageAltitude: "Unable to fetch Average Altitude",
        UnabletoFetchChartDetails: "Unable to Fetch Chart Details",
        Altitude: "Altitude (Meter)",
        Year: "Year",
        LocationClasses: "Location Classes",
        MeanofSpeed: "Average Speed (Kt)",
        MaxSpeed: "Max Speed (Kt)",
        IDs: "IDs",
        MeanofAltitude: "Average Altitude (Meter)",
        MaxAltitude: "Max Altitude (Meter)",
        placeholderPlatFormId: "Select PTT ID",
        placeholderSpeciesName:"Select Species",
        NumberofLocations: "Number of Locations",
        NumberofSpecies: "Number of Species",
        NumberofBirds: "Number of Birds",
        NoofLocations: "No. of Locations",
        NoofSpecies: "No. of Species",
        NoofBirds: "No. of Birds",
        ArgosReport: "ARGOS Report",
        GPSReport: "GPS Report",
        GSMReport: "GSM Report",
        Min: "Min",
        Max: "Max",
        Avg:"Avg",
        GSMReport: "GSM Report",
        Active: "Active",
        Inactive: "Inactive",
        Locations: "Locations",
        Unabletofetchbirdplatformids: "Unable to fetch Platformids",
        UnabletofetchSpeciesNames: "Unable to fetch Species Name",
        UnabletoFetchRawDataDetails: "Unable to Fetch Raw Data Details",
        UnabletoFetchAltitudeChartDetails: "Unable to Fetch Altitude Chart Details",
        SelectedItems: " Selected",
        SelectedAllItems: "all selected",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});