define({
    MMC: "تقرير MMC",
    PlatformID: "رمز الجهاز",
    MigrationStartDate: "تاريخ بداية الهجرة",
    MigrationEndDate: "تاريخ انتهاء الهجرة",
    Duration: "مدة(Days)",
    AverageSpeed: "سرعة(Kt)",
    AverageAltitude: "ارتفاع(Meter)",
    Distance: "المسافة(Km)",
    Locations: "الموقع",
    ReportDashBoard: "تقرير الألواح الرقمية",
    SpeciesName: "النوع",
    SensorType: "نوع جهاز الاستشعار",
    FromDate: "من تاريخ",
        ToDate: "إلى تاريخ",
    FetchIDs: "جلب الرموز",
    /*GenerateMMC: "توليد MMC",*/
    GenerateMMC:" انشاء تقرير MMC",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
       // MovementMetricCalculations: "معرف المنصة",
    PleaseSelectSpeciesName: "اختر نوع الطير",
        ddmmyyyy: "سنة - شهر - يوم",
    PleaseSelectPlatformId: "حدد رمز الجهاز",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    placeholderPlatFormId: "حدد رمز الجهاز",
        placeholderSensorType: "حدد نوع المستشعر",
        placeholderSpeciesName: "حدد اسم الأنواع",
    WinteringArea: "فترة الشتاء",
    SpringMigration: "هجرة الربيع",
    BreedingArea: "فترة الصيف",
    AutumnMigration: "هجرة الخريف",
    ExportReport: "إصدار تقرير",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    PleaseEnterFromDate: "ادخل من تاريخ",
    PleaseEnterToDate: "إدخال حتى تاريخ",
        InvalidInputs: "مدخلات غير صحيحة",
        ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    PleaseSelectSpeciesName: "يرجى اختيار نوع الطير",
    Unabletofetchbirdnames: "تعذر الحصول على أسماء الطيور",
    Unabletofetchplatformids: "تعذر توفير رموز الطيور",
    UnabletofetchbirdPTTIDdetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    NoResultFound: "لا توجد نتائج",
    MMC: "تقرير MMC",
    Speed: "(kt)متوسط ​​السرعة",
    Altitude: "(متوسط ​​الارتفاع (بالمتر",
    ArrivalDate: "تاريخ الوصول",
    DepartureDate: "تاريخ المغادرة",
    Active: "نشط",
    Inactive: "غير نشط",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
    ErrorinUpdate: "خطأ في التحديث",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    
});