define({
    Reports: "تقرير التتبع",
    FromDate: "من تاريخ",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    SensorType: "نوع جهاز الاستشعار",
    ToDate: "إلى تاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    FetchIDs: "جلب الرموز",
    ddmmyyyy: "سنة - شهر - يوم",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    GraphsBackgroundColor: "لون خلفية الرسوم البيانية",
    ExportReport: "إصدار تقرير",
    GenerateReport: "انشاء تقرير",
    ArgosandGPSSensorDatasummary: "Argos و GPS ، ملخص بيانات المستشعر",
    GPSGSMandArgosCounts: "Gps Gsm و Argos جمع بيانات",
    LocationClasses: "تصنيف الموقع",
    GPSLocationsTable: "جدول المواقع GPS",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    NoBirdIdsFound: 'لا يوجد رمز للطيور في الاختيار المحدد',
    UnabletoCollectbirdplatformids: "تعذر جمع رموز اجهزة الطيور",
    Youmustcheckatleastonecheckbox: " حدد رمز الجهاز",
    SensorTypeDataReport: "تقرير التتبع",
    IDs: "المعرف",
    Status: "الحالة الاجتماعية ",
    placeholderSensorType:"حدد نوع المستشعر",
    Inactive: "غير نشط",
    Active: "نشط",
    ReportDashBoard: "تقرير الألواح الرقمية",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    NoResultsFound: "لا توجد نتائج",
    GPSGSMandArgosDataCollection: "جمع بيانات نوع المستشعر",
    PlatformIDs: "رمز الجهاز",
    TotalLocations: "عدد المواقع الكلي",
    PleaseSelectIds: "حدد معرّف النظام الأساسي",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
    SensorType: "نوع جهاز الاستشعار",
    SpeciesName: "النوع",
    SelectPlatformID: "رمز الجهاز",
    placeholderSpeciesName: "حدد الأنواع",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    placeholderPTTID: " حدد رمز الجهاز",
    UnabletofetchbirdPTTIDS: "تعذر الحصول على رمز الطيور ",
    TrackingReport: "تقرير التتبع",
    TrackingReports: "تقارير التتبع : ",
    RawData: "تصدير البيانات الأولية",
    Active: "نشط",
    Inactive: "غير نشط",
    UnabletoFetchRawDataDetails: "تعذر جلب تفاصيل البيانات الأولية",
    Unabletofetchplatformids: "غير قادر على جلب تفاصيل معرف الطائر PPT",
    UnabletofetchSpeciesnames: "تعذر الحصول على هذا النوع أسماء",
    to: "إلى",
    SelectedItems: "محدد",
    SelectedAllItems: "الجميع المحدد",
    widgets: {
        homeButton: {
            "home": {
                "button": "Home",
                "title": "Default extent"
            }
        }
    },
});