define({
    root: ({
        SpeciesNames: "Species",
        BandID: "Band ID :",
        Age: "Age :",
        BirdWeight: "Bird Weight :",
        CaptureDate: "Capture Date :",
        CaptureTime: "Capture Time :",
        CommonName: "Common Name :",
        LastActiveDate: "Last Active Date :",
        Lat: "Lat :",
        LatinName: "Latin Name :",
        Long: "Long :",
        PurchaseYear: "Purchase Year :",
        ReleaseDate: "Release Date :",
        ReleaseTime: "Release Time :",
        Sensitive: "Sensitive :",
        SensorType: "Sensor Type :",
        SensorWeight: "Sensor Weight :",
        Sex: "Sex :",
        Site: "Site:",
        SpeciesID: "Species ID :",
        placeholderSelectBirdId: "Select Bird ID",
        placeholderSpeciesName: "Select Species",
        placeholderSelectBirdYear:"Select Bird Year",
        Status: "Status :",
        WingsLength: "Wings Length :",
        ChooseaBird: "Choose a Bird",
        select: "select",
        ChooseYear: "Choose Year",
        GetBirdInfo:"Get Bird Info",
        SelectBird: "Select bird ID",
        SelectYear: "Select year",
        PlatformId:"Platform Id :",
        SelectSpeciesNames: "Select Species",
        UnabletofetchbirdPTTIDS: "Unable to fetch bird PTT IDS",
        UnabletofetchBirdIdDetails: "Unable to fetch Bird Id Details",
        UnabletofetchBirdIds: "Unable to fetch Bird Ids",
        unabletofetchBirdNames: "unable to fetch Bird Names",
        NoResultsFound:"No Results Found",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
        Export: "Export",
        SelectedItems: "Selected",
        SelectedAllItems: "all selected",
        widgets: {
            homeButton: {
                "home": {
                    "button": "Home",
                    "title": "Default extent"
                }
            }
        },
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});