define({
    root: ({
        title: 'BirdTrackingPPTID',
        SensorType: "Sensor Type",
        select: "select",
        locationclasses: "locationclasses",
        PlatformID: "Platform ID",
        LocationClasses: "Location Classes",
        FromDate: "From Date",
        ToDate: "To Date",
        TimeInterval: "Time Interval",
        Argos: "Argos",
        GPS: "GPS",
        GSM: "GSM",
        PleaseSelectSensorType: "Select Sensor Type",
        PleaseSelectPlatformID: "Select Platform ID",
        PleaseEnterFromDate: "Enter From Date",
        PleaseEnterToDate: "Enter To Date",
        InvalidInputs: "Invalid Inputs",
        ToDateShouldbeGreaterthanFromDate: "To Date Should be Greater Than From Date",
        Run: "Run",
        StopOver: "Stop Over",
        ddmmyyyy: "dd - mm - yyyy",
        chkSeasonWise: "Season Wise Migration",
        Animate: "Animate",
        Density: "Density",
        Unabletofetchbirdplatformids: "Unable to fetch bird platform ids",
        NoResultFound: "No Results Found",
        UnabletofetchbirdPTTIDdetails: "Unable to fetch bird PTT ID details",
        UnabletogetAssignedids: "Unable to get Assigned ids",
        UnabletofetchLocClasses: "Unable to fetch Location Classes",
        placeholderPTTID: "Select Platform ID",
        SearchText: "Enter Here",
        placeholderSensorType:"Select Sensor Type",
        NoDataFound: "No.of records exceed the memory, please select the time interval to reduce the data.",
        ClearData: "No.of records exceed the memory, please clear the plotted Data.",
        SelectedItems: "Selected",
        TIhours: "Hrs",
        OK: "OK",
        Cancel: "Cancel",
        SelectAll: "Select All",
    }),
    "ar": 1,
    "da": 1,
    "de": 1,
    "es": 1,
    "et": 1,
    "fr": 1,
    "he": 1,
    "it": 1,
    "ja": 1,
    "ko": 1,
    "lv": 1,
    "lt": 1,
    "nl": 1,
    "nb": 1,
    "pl": 1,
    "pt-br": 1,
    "pt-pt": 1,
    "ro": 1,
    "ru": 1,
    "sv": 1,
    "zh": 1,
    "zh-cn": 1
});