define({

    title: 'BirdTrackingPPTID',
    ddmmyyyy: "سنة - شهر - يوم",
    SensorType: "نوع جهاز الاستشعار",
    select: "select",
    locationclasses: "تصنيف الموقع",
    PlatformID: "رمز الجهاز",
    LocationClasses: "تصنيف الموقع",
    FromDate: "من تاريخ",
    ToDate: "إلى تاريخ",
    TimeInterval: "الفترة الزمنية",
    Argos: "ارجوس",
    GPS: "جي بي اس",
    GSM: "جي اس ام",
    PleaseSelectSensorType: "يرجى تحديد نوع المستشعر",
    PleaseSelectPlatformID: " حدد رمز الجهاز",
    PleaseEnterFromDate: "الرجاء إدخال من التاريخ",
    PleaseEnterToDate: "الرجاء إدخال حتى التاريخ",
    InvalidInputs: "مدخلات غير صحيحة",
    ToDateShouldbeGreaterthanFromDate: "التاريخ الحالي يجب ان يكون اعلى من التاريخ السابق",
    Run: "تشغيل",
    StopOver: "نقطة توقف",
    chkSeasonWise: "الهجرة الموسمية  ",
    Animate: "تحريك",
    Density: "كثافة النقطة",
    Unabletofetchbirdplatformids: "تعذر توفير رموز الطيور",
    NoResultFound: "لا توجد نتائج",
    UnabletofetchbirdPTTIDdetails: "تعذر الحصول على تفاصيل معرفات الطيور",
    UnabletogetAssignedids: "تعذر الحصول على  الرموز المحددة",
    UnabletofetchLocClasses: "تعذر الحصول تصنيف الموقع",
    placeholderPTTID: " حدد رمز الجهاز",
    placeholderSensorType: " حدد نوع المستشعر",
    NoDataFound: "عدد السجلات كبير جداً ، يرجى تحديد الفترة الزمنية لتقليل البيانات.",
    ClearData: "عدد السجلات كبير جداً ، يرجى مسح البيانات المخططة.",
    SelectedItems: "محدد",
    TIhours: "ساعات",
    OK: "نعم",
    Cancel: "الغاء",
    SelectAll: "اختر الكل",
});